### ISSUE TITLE
The preview response data type should be improved

### ISSUE THREAD

**Issue by phax** [de4a-wp5/xml-schemas#16]
Currently `PreviewResponseType` just contains an `xsd:any`

A predefined wrapper to send base64:binary would be good. Also a predefined element for a "reference URL" as well.
So something like this:
```xml
<xs:choice>
  <xs:element name="payload" type="xs:base64Binary" />
  <xs:element name="url" type="xs:string" />
  <xs:element name="anyWrapper">
    <xs:complexType>
<xs:sequence>
  <xs:any namespace="##any" processContents="lax"/>
</xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:choice>
```

I think this better than just "any". What do you think?

**Comment by danieldecastrop** [comment]
Hi @phax I have discussed this with Javier Ferrero to delete this tag. This was intended as a data structure for the consent, but if it is accepted in the Owner in the response will come the ev and will be taken as accepted consent, if not, a typed error will be returned.

Regards
