### ISSUE TITLE
ErrorType too hard restrictions

### ISSUE THREAD

**Issue by andreasjberg** [de4a-wp5/xml-schemas#19]
- The CodeErrorType has a max length of 10. This will create heavy restrictions when defining the error codes for the connector. As an example, this effectively rules out the use of prefixes such as "de4a-" in our project-defined error-codes.
- The TextErrorType has a max length of 4000. This will make it impossible to display stack traces or other similarly verbose error messages crucial for effective debugging during development.

**Comment by danieldecastrop** [comment]
Hi!!

10 alphanumeric characters are enough to define an error code.

It is not recommended to return a stacktrace or a huge message in the response, for development you could use the logs to debug it.

Error messages should be as user friendly as possible in return message.

This has already been discussed in a call

Regards

**Comment by phax** [comment]
@danieldecastrop the problem here is, that we have a highly distributed system. We cannot assume, that everyone is fully "under control" of each and every logfile, so passing on information that help the other side (sender or receiver) maybe helpful (seen this in other large scale systems)

**Comment by danieldecastrop** [comment]
Hi @phax I have discussed it with javier Feerrero and he agrees to leave it like this, he does not apply a stacktrace or similar in the response its should be user friendly message.

Regards

**Comment by phax** [comment]
acknowledged
