### ISSUE TITLE
Element for the "Dynamic Discovery Process ID" is missing

### ISSUE THREAD

**Issue by phax** [de4a-wp5/xml-schemas#2]
As discovered today, the `ProcessID` for the routing information is missing.

Evtl. we also need a `ReturnProcessId` similar to the `ReturnServiceId`??

**Comment by danieldecastrop** [comment]
Hi, ProcessId and ReturnProcessId will be constant and will be obtained from the response of the smp

**Comment by phax** [comment]
I disagree here. The ProcessId is one of the query parameters of the SMP, not a response
