### ISSUE TITLE
Length limits in XML Schema are inconsistent

### ISSUE THREAD

**Issue by phax** [de4a-wp5/xml-schemas#35]
In many cases, you try to limit the XML Schema types with a `maxLength`.
In certain cases this is however not done, as e.g. with:
* element `AgentName` of type `cv:NameType`
* element `CanonicalEventCatalogUri` of type `xs:anyURI`
* all the child elements of `DataSubjectPerson` and `DataSubjectCompany` as they are based on the eIDAS types
* ...

In general it is imho bad practise to length limit the types in the XML Schema - that should be done on an upper level of the application.

**Comment by aosunacab** [comment]
It might considerate to limitate the data content in advance, I mean, the data processor (e.g. DO) could control data contents, length among others, but the message is already sent, It could be reasonable to have some limitations in advance?, as a first filter, furthermore those limitations were consensuated from the beggining in the model, I guess.

what do you think?

**Comment by aosunacab** [comment]
No, nothing to do with a technical solution, just I think that it doesn't hurt to have a data fits limitations

**Comment by phax** [comment]
Okay. Yes I agree with that - but I think the length restrictions should all be on the same place. So either all in XSD or all somewhere else. My best guess would be a Schematron, but I know you are reluctant to that

**Comment by aosunacab** [comment]
Indeed I am supporter of Schematron, but it was a members decision not to apply that validation layer level for this purposes. So, in this case, maybe we can include more lenght or whatever limitations in the XSDs as workaround

**Comment by aosunacab** [comment]
So, if some extra validation or limits update raise we will include them on the fly. May we close this issue by now?

**Comment by phax** [comment]
Fine for me
