### ISSUE TITLE
Similar to #44

### ISSUE THREAD

**Issue by phax** [de4a-wp5/xml-schemas#46]
* `AvailableSourcesType`
* `DomesticsEvidencesType`
* `ErrorListType`
* `ProvisionItemsType`

If you like....

**Comment by phax** [comment]
Sorry, I just saw, that
```
<xs:attribute ref="xml:lang" use="optional" default="en"/>
```
Was part of `DomesticsEvidencesType`.
Can you add this to `DomesticsEvidenceType` instead?
Having this per evidence makes more sense anyway

**Comment by aosunacab** [comment]
Yes, I just did like that:
https://github.com/de4a-wp5/xml-schemas/blob/ad3833d3fa9959f0637d0c68af6a70a3e942abfa/XSD/de4a/common-types.xsd#L49

**Comment by phax** [comment]
Cool thanks - missed that
